# Generated by Django 5.2.8 on 2025-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_modelstatus_stock_stockdata_delete_requeststock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True)),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
